services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - bugzkit-api
      - bugzkit-ui
    networks:
      - web

  bugzkit-api:
    container_name: bugzkit-api
    image: while1618/bugzkit-api:1.0.0
    restart: always
    environment:
      UI_URL: ${UI_URL:-https://bugzkit.com}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-root}
      USER_PASSWORD: ${USER_PASSWORD:-qwerty123}
      SMTP_USER: ${SMTP_USER:-username}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-password}
      JWT_SECRET: ${JWT_SECRET:-secret}
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      start_period: 10s
      interval: 30s
      retries: 3
    networks:
      - web

  postgres:
    container_name: postgres
    image: postgres:17.2-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bugzkit}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 10s
      interval: 30s
      retries: 3
    networks:
      - web

  redis:
    container_name: redis
    image: redis:7.4.1
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-root}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-root}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-root}", "ping"]
      start_period: 10s
      interval: 30s
      retries: 3
    networks:
      - web

  bugzkit-ui:
    container_name: bugzkit-ui
    image: while1618/bugzkit-ui:1.0.0
    restart: always
    environment:
      PORT: 5173
      ORIGIN: http://localhost:5173
    depends_on:
      - bugzkit-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      start_period: 10s
      interval: 30s
      retries: 3
    networks:
      - web

networks:
  web:
    driver: bridge
