services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=while1618@tutamail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  bugzkit-api:
    container_name: bugzkit-api
    image: while1618/bugzkit-api:1.0.0
    restart: always
    environment:
      UI_URL: ${UI_URL:-https://bugzkit.com}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-root}
      USER_PASSWORD: ${USER_PASSWORD:-qwerty123}
      SMTP_USER: ${SMTP_USER:-username}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-password}
      JWT_SECRET: ${JWT_SECRET:-secret}
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      start_period: 10s
      interval: 30s
      retries: 3

  postgres:
    container_name: postgres
    image: postgres:17.2-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bugzkit}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 10s
      interval: 30s
      retries: 3

  redis:
    container_name: redis
    image: redis:7.4.1
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-root}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-root}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-root}", "ping"]
      start_period: 10s
      interval: 30s
      retries: 3

  bugzkit-ui:
    container_name: bugzkit-ui
    image: while1618/bugzkit-ui:1.0.0
    restart: always
    environment:
      ORIGIN: http://localhost:5173
    depends_on:
      - bugzkit-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      start_period: 10s
      interval: 30s
      retries: 3
