services:
  reverse-proxy:
    image: traefik:v3.1
    container_name: traefik
    restart: always
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=your-email@example.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  bugzkit-api:
    container_name: bugzkit-api
    image: while1618/bugzkit-api:1.0.0
    restart: always
    environment:
      UI_URL: ${UI_URL:-https://bugzkit.com}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-root}
      USER_PASSWORD: ${USER_PASSWORD:-qwerty123}
      SMTP_USER: ${SMTP_USER:-username}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-password}
      JWT_SECRET: ${JWT_SECRET:-secret}
    depends_on:
      - postgres
      - redis
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.bugzkit.com`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=8080"

  postgres:
    container_name: postgres
    image: postgres:17.2-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-bugzkit}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 10s
      interval: 30s
      retries: 3
    networks:
      - web

  redis:
    container_name: redis
    image: redis:7.4.1
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-root}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-root}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-root}", "ping"]
      start_period: 10s
      interval: 30s
      retries: 3
    networks:
      - web

  bugzkit-ui:
    container_name: bugzkit-ui
    image: while1618/bugzkit-ui:1.0.0
    restart: always
    environment:
      PORT: 5173
      ORIGIN: https://bugzkit.com
    depends_on:
      - bugzkit-api
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=Host(`bugzkit.com`)"
      - "traefik.http.routers.ui.entrypoints=websecure"
      - "traefik.http.routers.ui.tls.certresolver=letsencrypt"
      - "traefik.http.services.ui.loadbalancer.server.port=5173"

volumes:
  letsencrypt:
networks:
  web:
    driver: bridge
