include:
  - docker-compose-api.dev.yml

services:
  bugzkit-ui:
    container_name: bugzkit-ui
    image: bugzkit-ui:dev
    build:
      context: ./frontend/svelte-kit
      dockerfile: Dockerfile
      target: dev
    ports:
      - "${UI_PORT:-5173}:${UI_PORT:-5173}"
    restart: always
    environment:
      PORT: ${UI_PORT:-5173}
      JWT_SECRET: ${JWT_SECRET:-secret}
      PUBLIC_APP_NAME: ${APP_NAME:-bugzkit}
      PUBLIC_API_URL: http://bugzkit-api:${API_PORT:-8080}
      DOMAIN_NAME: ${DOMAIN_NAME:-localhost}
    depends_on:
      - bugzkit-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${UI_PORT:-5173}"]
      start_period: 10s
      interval: 30s
      retries: 3
    networks:
      - web
