services:
  postgres:
    container_name: postgres
    image: postgres:17.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-bugzkit}
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 10s
      interval: 30s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web

  redis:
    container_name: redis
    image: redis:7.4.1
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-root}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-root}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-root}", "ping"]
      start_period: 10s
      interval: 30s
      retries: 3
    volumes:
      - redis_data:/data
    networks:
      - web

volumes:
  postgres_data:
  redis_data:

networks:
  web:
    driver: bridge
