name: Deploy CI
run-name: ${{ github.actor }} started CI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fail if not on master
        if: github.ref != 'refs/heads/master'
        run: echo "This workflow can only be run on the master branch." && exit 1

      - name: Fail if not run by owner
        if: github.actor != 'while1618'
        run: echo "This workflow can only be run by the owner." && exit 1

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: bugzkit
          file: docker-stack.prod.yml
          host: ${{ secrets.HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
