name: Spring Boot CI
run-name: ${{ github.actor }} started CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - backend/spring-boot/**
  pull_request:
    branches: [master]
    paths:
      - backend/spring-boot/**

jobs:
  build:
    defaults:
      run:
        working-directory: backend/spring-boot

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build
        run: mvn -B clean install -DskipTests

      - name: Lint
        run: mvn -B spotless:check

      - name: Unit tests
        run: mvn -B test

      - name: Integration tests
        run: mvn -B failsafe:integration-test failsafe:verify

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get package version
        id: pom-version
        run: |
          VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" backend/spring-boot/pom.xml | sed 's/-SNAPSHOT//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: backend/spring-boot
          file: backend/spring-boot/Dockerfile
          target: prod
          push: true
          tags: |
            ${{ vars.DOCKER_REPOSITORY_API }}:${{ steps.package-version.outputs.version }}
            ${{ vars.DOCKER_REPOSITORY_API }}:latest
